version: '3.4'
  
services:
  eagle:
     build:
       context: .
       dockerfile: Dockerfile
     environment:
        - ASPNETCORE_URLS=http://+:80
     ports:
        - "80:80"
     depends_on:
        - rabbitmq
        - redis

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
        - "6397:6397"

  rabbitmq:     
    image: rabbitmq:3.9-management
    ports:
        - "5627:5627"